# Generated by Django 5.1.14 on 2025-11-21 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_alter_uploadprocessingstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
