# Generated by Django 5.1.13 on 2025-11-21 07:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_account", "0001_initial"),
        ("music_monitor", "0005_alter_royaltydistribution_status_and_more"),
        ("royalties", "0001_initial"),
        ("stations", "0003_stationstaff_can_manage_compliance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_id",
                    models.CharField(
                        default="ZAMIO-CENTRAL-POOL", max_length=50, unique=True
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("currency", models.CharField(default="GHS", max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "total_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total money received from stations",
                        max_digits=15,
                    ),
                ),
                (
                    "total_paid_out",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total money paid to artists/publishers",
                        max_digits=15,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Central Account",
                "verbose_name_plural": "Platform Central Accounts",
            },
        ),
        migrations.CreateModel(
            name="StationAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_id", models.CharField(max_length=20, unique=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("currency", models.CharField(default="GHS", max_length=50)),
                (
                    "allow_negative_balance",
                    models.BooleanField(
                        default=False, help_text="Allow station to go into debt"
                    ),
                ),
                (
                    "credit_limit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Maximum negative balance allowed",
                        max_digits=15,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "total_spent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total spent on plays",
                        max_digits=15,
                    ),
                ),
                (
                    "total_plays",
                    models.IntegerField(
                        default=0, help_text="Total number of plays charged"
                    ),
                ),
                (
                    "station",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Station Account",
                "verbose_name_plural": "Station Accounts",
            },
        ),
        migrations.CreateModel(
            name="PlatformTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=20, unique=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("station_payment", "Station Payment"),
                            ("payout", "Payout to User"),
                            ("adjustment", "Manual Adjustment"),
                            ("refund", "Refund"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("description", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "platform_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="bank_account.platformaccount",
                    ),
                ),
                (
                    "play_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music_monitor.playlog",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stations.station",
                    ),
                ),
                (
                    "user_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bank_account.bankaccount",
                    ),
                ),
                (
                    "withdrawal_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="royalties.royaltywithdrawal",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["platform_account", "transaction_type"],
                        name="bank_accoun_platfor_4f567c_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="bank_accoun_timesta_99cf52_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StationTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.CharField(max_length=20, unique=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit/Top-up"),
                            ("play_charge", "Play Charge"),
                            ("refund", "Refund"),
                            ("adjustment", "Manual Adjustment"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("description", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "play_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music_monitor.playlog",
                    ),
                ),
                (
                    "station_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="bank_account.stationaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["station_account", "transaction_type"],
                        name="bank_accoun_station_a5f3a7_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="bank_accoun_timesta_13a33b_idx"
                    ),
                ],
            },
        ),
    ]
