# Generated by Django 5.1.14 on 2025-11-21 12:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_account', '0002_platformaccount_stationaccount_platformtransaction_and_more'),
        ('stations', '0003_stationstaff_can_manage_compliance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StationDepositRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='GHS', max_length=50)),
                ('payment_method', models.CharField(choices=[('mtn_momo', 'MTN Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('cash', 'Cash')], max_length=50)),
                ('reference', models.CharField(blank=True, help_text='Payment reference number', max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_deposits', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_requests', to='stations.station')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['station', 'status'], name='bank_accoun_station_6487ea_idx'), models.Index(fields=['status', 'requested_at'], name='bank_accoun_status_f153eb_idx')],
            },
        ),
    ]
