# Generated by Django 5.1.14 on 2025-11-21 05:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_monitor', '0004_alter_matchcache_track'),
        ('publishers', '0002_publisheraccountsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='royaltydistribution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Calculation'), ('calculated', 'Calculated'), ('approved', 'Approved for Payment'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('failed', 'Payment Failed'), ('disputed', 'Under Dispute'), ('withheld', 'Withheld')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='PublisherArtistSubDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_distribution_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=4, help_text='Total from parent distribution', max_digits=12)),
                ('publisher_fee_percentage', models.DecimalField(decimal_places=2, help_text="Publisher's commission %", max_digits=5)),
                ('publisher_fee_amount', models.DecimalField(decimal_places=4, help_text="Publisher's commission amount", max_digits=12)),
                ('artist_net_amount', models.DecimalField(decimal_places=4, help_text='Amount due to artist', max_digits=12)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending Distribution'), ('calculated', 'Calculated'), ('approved', 'Approved for Payment'), ('paid', 'Paid to Artist'), ('failed', 'Payment Failed'), ('disputed', 'Under Dispute')], default='pending', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_to_artist_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('agreement_reference', models.CharField(blank=True, help_text='Publisher-Artist agreement reference', max_length=100, null=True)),
                ('calculation_metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher_sub_distributions', to=settings.AUTH_USER_MODEL)),
                ('parent_distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_distributions', to='music_monitor.royaltydistribution')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_distributions', to='publishers.publisherprofile')),
            ],
            options={
                'ordering': ['-calculated_at'],
                'indexes': [models.Index(fields=['publisher', 'status'], name='music_monit_publish_3b5228_idx'), models.Index(fields=['artist', 'status'], name='music_monit_artist__19e9af_idx'), models.Index(fields=['parent_distribution'], name='music_monit_parent__eb019d_idx'), models.Index(fields=['status', 'calculated_at'], name='music_monit_status_5deb4f_idx')],
            },
        ),
    ]
