# Generated by Django 5.1.13 on 2025-11-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("music_monitor", "0005_alter_royaltydistribution_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlog",
            name="charged_at",
            field=models.DateTimeField(
                blank=True, help_text="When station was charged", null=True
            ),
        ),
        migrations.AddField(
            model_name="playlog",
            name="payment_error",
            field=models.TextField(
                blank=True, help_text="Error message if payment failed", null=True
            ),
        ),
        migrations.AddField(
            model_name="playlog",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("charged", "Charged"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Status of station payment for this play",
                max_length=20,
            ),
        ),
    ]
