# Generated by Django 5.1.15 on 2025-12-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_alter_track_active'),
        ('music_monitor', '0006_playlog_charged_at_playlog_payment_error_and_more'),
        ('stations', '0003_stationstaff_can_manage_compliance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlog',
            options={'ordering': ['-played_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='matchcache',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Processing'), ('verified', 'Verified Match'), ('processed', 'Converted to PlayLog'), ('failed', 'Failed to Process'), ('low_confidence', 'Low Confidence - Needs Review')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='playlog',
            name='royalty_distributed_at',
            field=models.DateTimeField(blank=True, help_text='When royalties were distributed', null=True),
        ),
        migrations.AddField(
            model_name='playlog',
            name='royalty_status',
            field=models.CharField(choices=[('pending', 'Pending Distribution'), ('calculated', 'Calculated'), ('distributed', 'Distributed'), ('failed', 'Distribution Failed'), ('withheld', 'Withheld')], default='pending', help_text='Status of royalty distribution to rights holders', max_length=20),
        ),
        migrations.AddField(
            model_name='playlog',
            name='verification_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('pending', 'Pending Review'), ('disputed', 'Disputed'), ('rejected', 'Rejected')], default='verified', help_text='Verification status of the match (artist/publisher perspective)', max_length=20),
        ),
        migrations.AlterField(
            model_name='playlog',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playlog',
            name='claimed',
            field=models.BooleanField(default=True, help_text='DEPRECATED: Use verification_status instead'),
        ),
        migrations.AlterField(
            model_name='playlog',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('charged', 'Charged'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Status of station payment for this play', max_length=20),
        ),
        migrations.AddIndex(
            model_name='matchcache',
            index=models.Index(fields=['station', 'matched_at'], name='music_monit_station_3070d7_idx'),
        ),
        migrations.AddIndex(
            model_name='matchcache',
            index=models.Index(fields=['status', 'processed'], name='music_monit_status_c92c96_idx'),
        ),
        migrations.AddIndex(
            model_name='playlog',
            index=models.Index(fields=['station', 'played_at'], name='music_monit_station_8d3c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='playlog',
            index=models.Index(fields=['track', 'played_at'], name='music_monit_track_i_57170e_idx'),
        ),
        migrations.AddIndex(
            model_name='playlog',
            index=models.Index(fields=['verification_status', 'payment_status'], name='music_monit_verific_f5c9f2_idx'),
        ),
        migrations.AddIndex(
            model_name='playlog',
            index=models.Index(fields=['royalty_status'], name='music_monit_royalty_82aec9_idx'),
        ),
        migrations.AddIndex(
            model_name='playlog',
            index=models.Index(fields=['is_archived', 'active'], name='music_monit_is_arch_48728b_idx'),
        ),
    ]
