# Generated by Django 5.1.15 on 2025-12-07 12:03
# Data migration to update existing PlayLog and MatchCache records with new status fields

from django.db import migrations


def migrate_playlog_status(apps, schema_editor):
    """
    Migrate existing PlayLog records to use new status fields.
    - Set verification_status based on claimed and flagged fields
    - Set royalty_status to 'pending' for all
    """
    PlayLog = apps.get_model('music_monitor', 'PlayLog')
    
    # Update playlogs with track assigned and claimed=True to verified
    verified_count = PlayLog.objects.filter(
        track__isnull=False,
        claimed=True,
        flagged=False
    ).update(verification_status='verified')
    
    # Update flagged playlogs to disputed
    disputed_count = PlayLog.objects.filter(
        flagged=True
    ).update(verification_status='disputed')
    
    # Update playlogs with track but not claimed to pending
    pending_count = PlayLog.objects.filter(
        track__isnull=False,
        claimed=False,
        flagged=False
    ).update(verification_status='pending')
    
    # Set claimed=True for all playlogs with tracks (for consistency)
    claimed_count = PlayLog.objects.filter(
        track__isnull=False,
        claimed=False
    ).update(claimed=True)
    
    print(f"✓ Migrated PlayLog status fields:")
    print(f"  - {verified_count} set to 'verified'")
    print(f"  - {disputed_count} set to 'disputed'")
    print(f"  - {pending_count} set to 'pending'")
    print(f"  - {claimed_count} set claimed=True")


def migrate_matchcache_status(apps, schema_editor):
    """
    Migrate existing MatchCache records to use new status field.
    """
    MatchCache = apps.get_model('music_monitor', 'MatchCache')
    
    # Update processed matches
    processed_count = MatchCache.objects.filter(
        processed=True,
        failed_reason__isnull=True
    ).update(status='processed')
    
    # Update failed matches
    failed_count = MatchCache.objects.filter(
        failed_reason__isnull=False
    ).update(status='failed')
    
    # Update pending matches with low confidence
    low_conf_count = MatchCache.objects.filter(
        processed=False,
        failed_reason__isnull=True,
        avg_confidence_score__lt=70
    ).update(status='low_confidence')
    
    # Update pending matches with good confidence
    verified_count = MatchCache.objects.filter(
        processed=False,
        failed_reason__isnull=True,
        avg_confidence_score__gte=70
    ).update(status='verified')
    
    # Update remaining pending matches (null confidence)
    pending_count = MatchCache.objects.filter(
        processed=False,
        failed_reason__isnull=True,
        status='pending'
    ).count()
    
    print(f"✓ Migrated MatchCache status fields:")
    print(f"  - {processed_count} set to 'processed'")
    print(f"  - {failed_count} set to 'failed'")
    print(f"  - {low_conf_count} set to 'low_confidence'")
    print(f"  - {verified_count} set to 'verified'")
    print(f"  - {pending_count} remain 'pending'")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - reset status fields to defaults
    """
    PlayLog = apps.get_model('music_monitor', 'PlayLog')
    MatchCache = apps.get_model('music_monitor', 'MatchCache')
    
    PlayLog.objects.all().update(
        verification_status='verified',
        royalty_status='pending'
    )
    
    MatchCache.objects.all().update(status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('music_monitor', '0007_alter_playlog_options_matchcache_status_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_playlog_status, reverse_migration),
        migrations.RunPython(migrate_matchcache_status, reverse_migration),
    ]
